name: Build and Release Go Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build binaries for all platforms
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd]
        goarch: [386, amd64, arm, arm64]
        exclude:
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: arm # no darwin/arm
          - goos: windows
            goarch: arm # go doesn't support windows/arm well
        include:
          - goos: windows
            extension: .exe
          - goos: linux
            extension: ""
          - goos: darwin
            extension: ""
          - goos: freebsd
            extension: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p dist
          go build \
            -trimpath \
            -ldflags "-w -s -X main.version=${{ github.ref_name }}" \
            -tags "nobadger,nomysql,nopgx" \
            -o dist/seedersync-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }} ${{ github.workspace }}

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
